# Generated by Django 4.0.4 on 2024-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellergroupsmodel',
            name='contacts_group',
            field=models.JSONField(null=True),
        ),
    ]
