# Generated by Django 4.0.4 on 2024-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_sellergroupsmodel_contacts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellergroupsmodel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellergroupsmodel',
            name='restrict',
            field=models.BooleanField(null=True),
        ),
    ]
