# Generated by Django 4.0.4 on 2024-02-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='complement',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='street',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
