# Generated by Django 4.0.4 on 2024-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_usermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='cnpj',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
