# Generated by Django 4.0.4 on 2024-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_sellermodel_cnpj_alter_sellermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
