# Generated by Django 4.0.4 on 2024-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_sellermodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellermodel',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='plan',
            field=models.BooleanField(default=False),
        ),
    ]
